version: '3.8'
services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - nest-postgres
  #   env_file:
  #     - .env

  casl-api-postgres:
    image: postgres:14
    container_name: casl-api-postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - casl-api-postgres:/var/lib/postgresql/data

volumes:
  casl-api-postgres:
    name: casl-api-postgres-db
